services:
  app:
    image: gauravmrjatt/instant-panel:latest
    container_name: instant-panel
    ports:
      - "3000:3000"  # Expose app on port 3000
    environment:
      - help_mail=test@gmail.com
      - PORT=3000
      - DB_URL=mongodb://mongo:27017/abc  # Use the service name 'mongo' for the connection
      - domain=http://localhost:3000
    volumes:
      - ./src:/app/src  # Bind local 'src' folder to the container's 'src' folder
      - /app/node_modules  # Persist node_modules for better performance (optional)
    depends_on:
      - mongo  # Ensure mongo service starts before the app service

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017"  # Expose MongoDB port
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount Prometheus configuration
    depends_on:
      - app  # Ensure the app service starts before Prometheus

volumes:
  mongo-data:
