services:
  # app:
  #   build: .
  #   container_name: instant-panel
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./server:/app/server   # Mount the 'server' folder   # Ensure container-only node_modules
  #   depends_on:
  #     - mongo
  #     - redis
  #     - rabbitmq
  #   # command: npm run st # Ensures Nodemon starts the app

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - app

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   volumes:
  #     - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongo-data:
  redis-data:
  rabbitmq-data:

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: ${SERVICE_USER_RABBITMQ}
      RABBITMQ_DEFAULT_PASS: ${SERVICE_PASSWORD_RABBITMQ}

    ports:
      - "5672:5672"
      - "15672:15672"
      - "5552:5552"

    command:
      - sh
      - -ec
      - |
        rabbitmq-plugins enable --offline rabbitmq_stream rabbitmq_stream_management
        printf "stream.listeners.tcp.default = 5552\n" >/etc/rabbitmq/rabbitmq.conf
        exec rabbitmq-server

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/