scrape_configs:
  - job_name: "backend"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:9092"]
        labels:
          service: "instant-panel"
          instance: "primary"

  - job_name: "rabbitmq"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]
        labels:
          service: "rabbitmq"

  - job_name: "mongodb"
    scrape_interval: 15s
    static_configs:
      - targets: ["mongodb-exporter:9216"]
        labels:
          service: "mongodb"

  - job_name: "redis"
    scrape_interval: 15s
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          service: "redis"

  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "grafana"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana:3000"]
        labels:
          service: "grafana"
